# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49274ede5573d972ed29dbe0ece83c9dd43916077c39de7999785205e41a3995758831b575e0af2572f66cb93da1c235feea32c61d802c5cd67d87275fcb5f39

test:
  secret_key_base: b0963e5317d27632bc3c22522221e50b75000612eda32575e7dc0a2746fa3eba772fa6999ba1a51ebddf03934942fb83639205a747b99d5eab6de9a5193449dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
